version: 2

sources:
  - name: omio
    schema: omio_stage
    tables:
      - name: stage_bookings
      - name: stage_passengers
      - name: stage_segments
      - name: stage_tickets
      - name: stage_currency

models:
  - name: raw_bookings
    description: "Daily view of Omio bookings filtered for previous-day data."
    columns:
      - name: booking_id
        description: "Unique identifier for each booking."
        tests:
          - unique
          - not_null
      - name: booking_created_at
        description: "Timestamp when the booking was created."
        tests:
          - not_null
      - name: booking_updated_at
        description: "Timestamp when the booking was last updated."
      - name: partner_id_offer
        description: "Partner ID for the offer linked to this booking."
      - name: booking_currency
        description: "Currency chosen to make the booking."
      - name: booking_price
        description: "Total booking price."
      - name: booking_status
        description: "Current Status of the booking"
        tests:
          - accepted_values:
              values: ['confirmed', 'pending', 'canceled']
              severity: warn
      - name: raw_meta
        description: "contains the details on from which platform the specific booking came from."

  - name: raw_segments
    description: "Daily view of Omio travel segments (previous day)."
    columns:
      - name: segment_id
        description: "Unique identifier for each segment."
        tests:
          - unique
          - not_null
      - name: booking_id
        description: "Booking identifier associated with the segment."
        tests:
          - not_null
          - relationships:
              to: ref('raw_bookings')
              field: booking_id
      - name: carrier_name
        description: "Name of the travel carrier."
      - name: departuredatetime
        description: "Departure time of the segment."
        tests:
          - not_null
      - name: arrivaldatetime
        description: "Arrival time of the segment."

  - name: raw_tickets
    description: "Daily view of Omio tickets (previous day)."
    columns:
      - name: ticket_id
        description: "Unique identifier for each ticket."
        tests:
          - unique
          - not_null
      - name: booking_id
        description: "Booking identifier linked to this ticket."
        tests:
          - not_null
          - relationships:
              to: ref('raw_bookings')
              field: booking_id
      - name: booking_price
        description: "Total booking price."
      - name: booking_currency
        description: "Currency used for this ticket booking."
      - name: issued_at
        description: "Date and time when ticket was issued."
        tests:
          - not_null

  - name: raw_passengers
    description: "Daily view of Omio passengers (previous day)."
    columns:
      - name: passenger_id
        description: "Unique identifier for each passenger."
        tests:
          - unique
          - not_null
      - name: booking_id
        description: "Booking ID linked to the passenger."
        tests:
          - not_null
          - relationships:
              to: ref('raw_bookings')
              field: booking_id
      - name: type
        description: "Passenger type (e.g., Adult, Child)."
      - name: age
        description: "Passenger age if available."
  
  - name: raw_currency
    description: "Daily currency exchange rates relative to EUR"
    columns:
      - name: date
        description: "Date when the rate was recorded"
      - name: currency_code
        description: "3-letter ISO currency code (e.g. USD, GBP, CHF)"
      - name: rate_to_eur
        description: "Exchange rate against Euro"
