name: omi_dbt
version: 1.0.0
config-version: 2

profile: omi_dbt

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  omi_dbt:
    +database: inspiring-ring-382618
    +schema: omio  # base logical schema (dataset)
    staging:
      +schema: raw
      +materialized: table
    core:
      +schema: core
      +materialized: table
